parameters:
#    nectalis_curriculum.example.class: Nectalis\CurriculumBundle\Example

services:
#    nectalis_curriculum.example:
#        class: %nectalis_curriculum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
